server:
  port: 8080

spring:
  datasource:
    username: root
    password: dtt123456
    url: jdbc:mysql://159.75.7.57:3306/qzcocllection?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 6144MB
      max-request-size: 6144MB
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
